package com.example.oauth2case.entity;

import java.util.Date;

public class TbPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.id
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.parent_id
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private Long parentId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.name
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private String name;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.enname
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private String enname;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.url
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private String url;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.description
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private String description;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.created
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private Date created;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.updated
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    private Date updated;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.id
     *
     * @return the value of tb_permission.id
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public Long getId() {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.id
     *
     * @param id the value for tb_permission.id
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.parent_id
     *
     * @return the value of tb_permission.parent_id
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.parent_id
     *
     * @param parentId the value for tb_permission.parent_id
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.name
     *
     * @return the value of tb_permission.name
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public String getName() {
        return name;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.name
     *
     * @param name the value for tb_permission.name
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.enname
     *
     * @return the value of tb_permission.enname
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public String getEnname() {
        return enname;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.enname
     *
     * @param enname the value for tb_permission.enname
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setEnname(String enname) {
        this.enname = enname;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.url
     *
     * @return the value of tb_permission.url
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public String getUrl() {
        return url;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.url
     *
     * @param url the value for tb_permission.url
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.description
     *
     * @return the value of tb_permission.description
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public String getDescription() {
        return description;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.description
     *
     * @param description the value for tb_permission.description
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.created
     *
     * @return the value of tb_permission.created
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public Date getCreated() {
        return created;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.created
     *
     * @param created the value for tb_permission.created
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.updated
     *
     * @return the value of tb_permission.updated
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.updated
     *
     * @param updated the value for tb_permission.updated
     *
     * @mbg.generated Sat Nov 02 23:12:39 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }


    ////*******自定义开始********/
    //***********自定义结束****////
}
