package com.example.oauth2case.entity;

import java.util.Date;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.username
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    private String username;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    private String password;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    private String phone;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.create_time
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    private Date created;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.update_time
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    private Date updated;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public Long getId() {
        return id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.username
     *
     * @return the value of tb_user.username
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public String getUsername() {
        return username;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.username
     *
     * @param username the value for tb_user.username
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public String getPassword() {
        return password;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public String getPhone() {
        return phone;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.create_time
     *
     * @return the value of tb_user.create_time
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public Date getCreated() {
        return created;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.create_time
     *
     * @param created the value for tb_user.create_time
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.update_time
     *
     * @return the value of tb_user.update_time
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.update_time
     *
     * @param updated the value for tb_user.update_time
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }


    ////*******自定义开始********/    
    //***********自定义结束****////
}
