package com.example.oauth2case.mapper;

import com.example.oauth2case.entity.TbUser;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    int insert(TbUser record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    int insertSelective(TbUser record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    TbUser selectByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    int updateByPrimaryKeySelective(TbUser record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Sat Nov 02 23:52:01 CST 2019
     */
    int updateByPrimaryKey(TbUser record);


    ////*******自定义开始********/

    TbUser selectUserByName(String username);

    //***********自定义结束****////
}
