server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/mdzz_seckill
    username: root
    password: 12345678
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.example.oauth2case.entity
  mapper-locations: classpath:mappers/*.xml
